### ISSUE TITLE
junit:junit-dep is no longer needed for newer JUnit releases

### ISSUE THREAD

**Issue by jdhoek** [stefanbirkner/system-rules#11]
With system-rules 1.4.0, JUnit 4.11, and Maven, I got this:

> [WARNING] The POM for junit:junit-dep:jar:4.9.1-SNAPSHOT is missing, no dependency information available

To use system-rules with JUnit 4.11, it seems necessary to exclude `junit:junit-dep` from its dependencies (if using Maven):

```
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.stefanbirkner</groupId>
      <artifactId>system-rules</artifactId>
      <version>1.4.0</version>
      <scope>test</scope>
      <!-- junit:junit-dep is deprecated, and junit:junit replaces it. -->
      <exclusions>
        <exclusion>
          <groupId>junit</groupId>
          <artifactId>junit-dep</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

This works; newer releases of `junit:junit` seem to have subsumed `junit:junit-dep`.

I'm not sure what a good solution would be. Shouldn't `system-rules` depend on `junit:junit` instead? This is the message included in the `junit-dep` POM:

> The artifact junit:junit does not contain Hamcrest anymore but declares a dependency to Hamcrest. Thus, junit:junit-dep has become obsolete.

**Comment by urbandroid** [comment]
intellij complaints: (test omitted for conflict with 4.12)

**Comment by stefanbirkner** [comment]
@urbandroid: Can you please elaborate on the IntelliJ problem. I don't understand it.

**Comment by urbandroid** [comment]
> @urbandroid: Can you please elaborate on the IntelliJ problem. I don't understand it.

Of course @stefanbirkner 

For a setup like this
`     <dependency>
         <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.stefanbirkner</groupId>
            <artifactId>system-rules</artifactId>
            <version>1.16.0</version>
            <scope>test</scope>
        </dependency>`

Maven and intellij omits the junit:4.11 dependency that comes from system-rules:1.16.0 it works but it is annoying.

I looked through the system-rules pom to locate source of this problem and i think i found. Because 
`    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit-dep</artifactId>
      <version>[4.9,)</version>
      <scope>compile</scope>
    </dependency>`
This part clearly indicates that anything above or equal to 4.9 is acceptable. Since the biggest version for junit-dep is 4.11 system-rules can only go to version 4.11 if junit:junit with a higher version used in project this annoyance occurs.

i changed system-rules dependency to junit:junit and problem is gone.

i'm not sure that if it is related to this issue anymore.

**Comment by damianszczepanik** [comment]
Mentioned dependency is also available in Jenkins repository:
```
[INFO] --------------------------------[ hpi ]---------------------------------
Downloading from incrementals: https://repo.jenkins-ci.org/incrementals/junit/junit-dep/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/junit/junit-dep/maven-metadata.xml
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit-dep/maven-metadata.xml (563 B at 278 B/s)
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/maven-metadata.xml (621 B at 266 B/s)
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/4.9/junit-dep-4.9.pom
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/4.9/junit-dep-4.9.pom (2.3 kB at 8.1 kB/s)
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/4.10/junit-dep-4.10.pom
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/4.10/junit-dep-4.10.pom (2.3 kB at 7.6 kB/s)
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/4.11-beta-1/junit-dep-4.11-beta-1.pom
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/junit/junit-dep/4.11-beta-1/junit-dep-4.11-beta-1.pom (2.0 kB at 7.0 kB/s)
[WARNING] The artifact junit:junit-dep:jar:4.11-beta-1 has been relocated to junit:junit:jar:4.11-beta-1: The artifact junit:junit does not contain Hamcrest anymore but declares a dependency to Hamcrest. Thus, junit:junit-dep has become obsolete.
```
