### ISSUE TITLE
Log on failure mode

### ISSUE THREAD

**Issue by binkley** [stefanbirkner/system-rules#19]
Hi, I've coded a log-on-failure mode which is similar to log-only however will log to the standard stream for failed tests.  This seems to capture the best of worlds:
* Passing tests are quiet and do not log to stream
* Failing tests are noisy and do log to stream

I have a fork with these changes.  Would you like a pull request?

https://github.com/binkley/system-rules

Cheers,
--binkley

**Comment by stefanbirkner** [comment]
Fixed with 6110562140c5bd925c9a9c09a21a88e0166ea1b4 in release 1.10.0
