### ISSUE TITLE
TextFromStandardInputStream does not cover IOExceptions

### ISSUE THREAD

**Issue by almondtools** [stefanbirkner/system-rules#25]
I recently needed a System.in that causes an IOException (in a unit test). E.g method throwExceptionOnInputEnd(IOException e). Implementation should be simple.

I would provide a pull request if you want to delegate the work.

**Comment by stefanbirkner** [comment]
Just to avoid any misunderstanding: `System.in` has to provide a specified amount of text and afterwards throw an exception? Or is it enough if it simply throws an exception.

**Comment by almondtools** [comment]
I needed only the feature of throwing an IOException.

But what should TextFromStandardInputStream do if one calls provideText and throwException on the same Object. I think the most consistent way is to provide the text (as long as read() != -1), and then (if read() == -1) throw the IOException. Yet I do not need this feature

**Comment by stefanbirkner** [comment]
Thanks for the info. I need this in order to make a good decision about how to solve the problem.
