### ISSUE TITLE
sbt will choose commons-io:20030203.000550 as dependency

### ISSUE THREAD

**Issue by macdao** [stefanbirkner/system-rules#28]
in pom.xml
```xml
<groupId>commons-io</groupId>
<artifactId>commons-io</artifactId>
<version>[2.0,)</version>
```

it will cause sbt choose commons-io:20030203.000550 which is a quite old version without org/apache/commons/io/IOUtils

**Comment by stefanbirkner** [comment]
It is fixed. Please update to version 1.12.1.
