### ISSUE TITLE
Undocumented Apache Commons IO dependency

### ISSUE THREAD

**Issue by wheelerlaw** [stefanbirkner/system-rules#31]
In PrintStreamRule.java and ProvideSystemPropertyTest.java there is an undocumented dependency on Apache Commons IO. Ideally, the dependency on Apache Commons should be removed if this library is to be used with just the JRE system library and JUnit. Otherwise, at the very least, it needs to be documented.

**Comment by stefanbirkner** [comment]
Why do you need them to be documented? Are you building your software without a build tool that automatically fetches transitive dependencies?

**Comment by stefanbirkner** [comment]
Fixed: 09dbb84a2577194fb9639c4ab957a1f3cd6c6388

Thank you for pointing to this problem.
