### ISSUE TITLE
maven pick a snapshot dependency of commons-io

### ISSUE THREAD

**Issue by laurentleseigneur** [stefanbirkner/system-rules#32]
when organization uses system-rules for testing, specific maven settings agains maven repo & mirrors makes it hard to resolve commons-io to 2.5-SNAPSHOT as suggested in 1.12.1 in a smart way, specially on CI build on docker 

i suggests to fix version instead of allowing a range.

https://github.com/stefanbirkner/system-rules/pull/30

**Comment by akhleung** [comment]
Having the same issue, I think -- my builds are failing because there's a dependency on `commons-io:jar:2.6-SNAPSHOT`.

**Comment by stefanbirkner** [comment]
I think that version ranges are the best way for defining the versions of a library's dependencies. If you want to have a fixed version of `commons-io` for your test then you can add

    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>[2.5]</version>
      <scope>test</scope>
    </dependency>

to your `pom.xml`.

**Comment by laurentleseigneur** [comment]
Thanks  for your response Stefan.

I already applied this to make version 1.12.1 work as expected, and the initial goal of my PR was to prevent users having the same issue.

If you want to stay with this ranged-version pattern, which i understand, just close my PR, but may be you could add a guidance paragraph in the README.md to avoid this confusing maven dependency resolutions.

**Comment by stefanbirkner** [comment]
System Rules 1.15.0 does not depend on commons-io anymore.
