### ISSUE TITLE
Java 9 compatibility?

### ISSUE THREAD

**Issue by szpak** [stefanbirkner/system-rules#52]
I use the system-rules in some framework dependent projects to test "untestable" things. As Java 9 is approaching quickly I was wondering if system-rules can be used with it, especially that there is a lot of "hack" used to do the things.

I wanted to give it a [try](https://github.com/szpak/system-rules/commits/java9), but it seems there are some Maven plugins required to be [upgraded](https://travis-ci.org/szpak/system-rules/jobs/276508565) (probably the same as some libraries) I decided to just create that issue to consider checking that compatibility one sunny day.

**Comment by stefanbirkner** [comment]
I built System Rules with Java 9 and it was successful (all tests are green): https://travis-ci.org/stefanbirkner/system-rules/builds/279670791 Next step is to enable JDK9 on Travis.

**Comment by szpak** [comment]
Great to hear!

Btw, did you mean "AppVeyor" instead of "Travis"? In the aforementioned link there is already a Travis build with Java 9.

**Comment by stefanbirkner** [comment]
No, I mean Travis. The branch under test has three commits and you only see the last one. Here is the diff of the branch: https://github.com/stefanbirkner/system-rules/compare/java9

**Comment by stefanbirkner** [comment]
Fixed by 2361ee6675e549001b9364d1a6cdea21e047bc24
