### ISSUE TITLE
Missing 0.16.1 tag on GitHub

### ISSUE THREAD

**Issue by szpak** [stefanbirkner/system-rules#54]
There is missing the latest tag 0.16.1 on GitHub:
https://github.com/stefanbirkner/system-rules/releases
(probably was not pushed to a remote repo)

**Comment by stefanbirkner** [comment]
Good catch. Thanks.

The tag is now pushed to the remote repo.

**Comment by szpak** [comment]
If you were a Gradle user I would suggest you [CDeliveryBoy])https://github.com/szpak/CDeliveryBoy/) a try to release automatically from Travis and have no problems with missing tags :)

**Comment by stefanbirkner** [comment]
Fortunately I can use Maven on this project ;-)
