### ISSUE TITLE
No coverage of System.exit with Jacoco

### ISSUE THREAD

**Issue by AlexLefranc** [stefanbirkner/system-rules#79]
Hi,

I try your rules (really useful for env variables), but when I use jacoco, the report don't see coverage of System.exit with ExpectedSystemExit. Do you know this problem ?

Thanks for your help, and your work.

**Comment by stefanbirkner** [comment]
Sorry for the late answer. This is a duplicate of #4 and therefore a problem of JaCoCo: jacoco/jacoco#117
